# Generated by Django 3.2 on 2021-04-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100, verbose_name='产品名称')),
                ('cas', models.CharField(max_length=100, verbose_name='cas号')),
                ('falias', models.CharField(max_length=100, verbose_name='英文别名')),
                ('calias', models.CharField(max_length=100, verbose_name='中文别名')),
                ('pickup_date', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
            ],
            options={
                'verbose_name_plural': '产品别名',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(db_index=True, max_length=500, verbose_name='产品名称')),
                ('cas', models.CharField(db_index=True, max_length=100, verbose_name='cas号')),
                ('specs', models.CharField(db_index=True, max_length=100, null=True, verbose_name='产品规格')),
                ('status', models.CharField(db_index=True, max_length=800, null=True, verbose_name='产品状态')),
                ('price', models.CharField(db_index=True, max_length=100, null=True, verbose_name='产品价格')),
                ('purity', models.CharField(db_index=True, max_length=100, null=True, verbose_name='产品纯度')),
                ('source_url', models.CharField(db_index=True, max_length=400, verbose_name='产品链接')),
                ('source', models.CharField(choices=[('Mce', 'Mce'), ('xlsw', '西利生物')], db_index=True, max_length=100, verbose_name='产品来源')),
                ('pickup_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='采集时间')),
            ],
            options={
                'verbose_name_plural': '产品规格',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(db_index=True, max_length=20, unique=True)),
                ('pwd', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uname'], name='app_user_uname_489a97_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['pname', 'cas', 'source'], name='app_propert_pname_7fc58d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['cas', 'source', 'specs', 'source_url', 'purity'], name='app_propert_cas_4ae7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='alias',
            index=models.Index(fields=['pname', 'cas', 'falias', 'calias'], name='app_alias_pname_9d2d66_idx'),
        ),
    ]
