# Generated by Django 2.2 on 2021-03-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chem960VipCompany',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, max_length=100, verbose_name='公司名称')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Chem960Vip',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('update_time', models.DateField(auto_created=True)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
            ],
            options={
                'verbose_name_plural': '公司名称库',
            },
        ),
        migrations.CreateModel(
            name='Company_info',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('link_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('telephone', models.CharField(blank=True, max_length=100, verbose_name='固话')),
                ('mobile', models.CharField(blank=True, max_length=100, verbose_name='手机')),
                ('qq', models.CharField(blank=True, max_length=100, verbose_name='qq号')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='公司地址')),
                ('product_num', models.CharField(blank=True, max_length=100, verbose_name='产品数量')),
                ('company_type', models.CharField(blank=True, max_length=100, verbose_name='公司类型')),
                ('scope', models.CharField(blank=True, max_length=500, verbose_name='主营产品')),
                ('cooperate_years', models.CharField(blank=True, max_length=50, verbose_name='合作年限')),
                ('source', models.CharField(max_length=100, verbose_name='数据源网站')),
                ('source_url', models.CharField(max_length=100, verbose_name='数据源网站链接')),
                ('update_time', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '公司信息详情',
                'ordering': ('-product_num',),
            },
        ),
        migrations.CreateModel(
            name='Ptinfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('pt_num', models.CharField(blank=True, max_length=100, verbose_name='平台数据源数量')),
                ('pt_sources', models.CharField(max_length=255, verbose_name='平台数据源')),
                ('product_num_max', models.CharField(blank=True, max_length=100, verbose_name='最大产品数')),
            ],
            options={
                'verbose_name_plural': '平台统计信息',
                'ordering': ['-pt_num'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20, unique=True)),
                ('pwd', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='UserMonitor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('IP', models.CharField(blank=True, max_length=100, verbose_name='IP地址')),
                ('localtime', models.CharField(blank=True, max_length=100, verbose_name='访问时间')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='访问地址')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='次数')),
            ],
            options={
                'verbose_name_plural': '平台访问信息',
                'ordering': ['-localtime'],
            },
        ),
        migrations.AddIndex(
            model_name='usermonitor',
            index=models.Index(fields=['name'], name='app_usermon_name_abad4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uname'], name='app_user_uname_489a97_idx'),
        ),
        migrations.AddIndex(
            model_name='ptinfo',
            index=models.Index(fields=['company_name'], name='app_ptinfo_company_de5fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='company_info',
            index=models.Index(fields=['company_name', 'source'], name='app_company_company_accf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_name'], name='app_company_company_af7f51_idx'),
        ),
        migrations.AddIndex(
            model_name='chem960vipcompany',
            index=models.Index(fields=['companyname'], name='app_chem960_company_71a657_idx'),
        ),
    ]
